const traitNamespace = rules => {
  class ChainLink {
    constructor(rules) {
      this.rules = rules
    }

    toString() {
      return this.rules
    }
  }

  Object.keys(rules).forEach(option => {
    Object.defineProperty(ChainLink.prototype, option, {
      get() {
        return new ChainLink(this.rules.concat(rules[option]))
      },
    })
  })

  return new ChainLink([rules.default])
}

export const transition = traitNamespace({
  d1: `transition-duration: 100ms;`,
  d2: `transition-duration: 200ms;`,
  d3: `transition-duration: 300ms;`,
  d4: `transition-duration: 400ms;`,
  d5: `transition-duration: 500ms;`,
  d6: `transition-duration: 600ms;`,
  bezier: `transition-timing-function: cubic-bezier(0.68, -0.55, 0.265, 1.55);`,
  ease: `transition-timing-function: ease;`,
  ease_in: `transition-timing-function: ease-in;`,
  ease_out: `transition-timing-function: ease-out;`,
  ease_in_out: `transition-timing-function: ease-in-out;`,
})

export const media = {
  giant: `@media only screen and (max-width: 1170px)`,
  desktop: `@media only screen and (max-width: 992px)`,
  tablet: `@media only screen and (max-width: 768px)`,
  phone: `@media only screen and (max-width: 376px)`,
}

export const zIndexes = {
  zIndexHeaderOverlay: `z-index: 500`,
  zIndexheader: `z-index: 400`,
  zIndexSideNav: `z-index: 400`,
  zIndexPageOverlay: `z-index: 300`,
  zIndexBackdrop: `z-index: 200`,
  zIndexInlineOverlay: `z-index: 100`,
  zIndexnegative: `z-index: -99`,
}

export const typography = traitNamespace({
  f1: `font-size: 3rem;`,
  f2: `font-size: 2.25rem;`,
  f3: `font-size: 1.5rem;`,
  f4: `font-size: 1.25rem;`,
  f5: `font-size: 1rem;`,
  f6: `font-size: .875rem;`,
  f7: `font-size: .75rem;`,

  interui: `font-family: 'Inter UI', sans-serif;`,
  mono: `font-family: "Input Mono", "Menlo", "Inconsolata", "Roboto Mono", "Consolas", monospace;`,

  regular: `font-weight: 400;`,
  medium: `font-weight: 500;`,
  bold: `font-weight: 700;`,
  black: `font-weight: 900;`,

  normal: `font-style: normal;`,
  italic: `font-style: italic;`,

  lh16: `line-height: 1.6;`,
  lh14: `line-height: 1.4;`,
  lh12: `line-height: 1.2;`,

  uppercase: `text-transform: uppercase;`,
  right: 'text-align: right;',
  left: 'text-align: left;',
  center: 'text-align: center;',
  capitalise: `text-transform: capitalize;`,
  pre_line: `white-space: pre-line;`,
  nowrap: `white-space: nowrap;`,
  no_underline: `text-decoration: none;`,
  truncate: `
    white-space: nowrap;
    overflow-x: hidden;
    text-overflow: ellipsis;
    max-width: 100%;
  `,
})

export const border = traitNamespace({
  solid: `border-style: solid;`,
  dotted: `border-style: dotted;`,
  ba: `border-style: solid; border-width: 1px;`,
  bt: `border-top-style: solid; border-top-width: 1px;`,
  br: `border-right-style: solid; border-right-width: 1px;`,
  bb: `border-bottom-style: solid; border-bottom-width: 1px;`,
  bl: `border-left-style: solid; border-left-width: 1px;`,
  bn: `border-style: none; border-width: 0;`,
  br0: `border-radius: 0;`,
  br1: `border-radius: .125rem;`,
  br2: `border-radius: .25rem;`,
  br3: `border-radius: .5rem;`,
  br4: `border-radius: 1rem;`,
  br5: `border-radius: 2rem;`,
  bw0: `border-width: 0;`,
  bw1: `border-width: .125rem;`,
  bw2: `border-width: .25rem;`,
  bw3: `border-width: .5rem;`,
  bw4: `border-width: 1rem;`,
  bw5: `border-width: 2rem;`,
})

export const flex = traitNamespace({
  default: `display: flex;`,
  inline: `display: inline-flex;`,
  vertical: `flex-direction: column;`,
  align_center: `align-items: center;`,
  align_start: `align-items: flex-start;`,
  align_end: `align-items: flex-end;`,
  align_baseline: `align-items: baseline;`,
  align_stretch: `align-items: stretch;`,
  center: `justify-content: center;`,
  center_both: `justify-content: center; align-items: center;`,
  justify_start: `justify-content: flex-start;`,
  justify_end: `justify-content: flex-end;`,
  justify_space_btw: `justify-content: space-between;`,
  justify_space_around: `justify-content: space-around;`,
  wrap: `flex-wrap: wrap;`,
  fg0: `flex-grow: 0;`,
  fg1: `flex-grow: 1;`,
  fg2: `flex-grow: 2;`,
})

export const grid = traitNamespace({
  default: `display: grid;`,
  auto_rows: `grid-template-rows: auto;`,
  auto_cols: `grid-template-columns: auto;`,
  g0: `grid-gap: 0;`,
  g025: `grid-gap: 0.25rem;`,
  g05: `grid-gap: 0.5rem;`,
  g1: `grid-gap: 1rem;`,
  g15: `grid-gap: 1.5rem;`,
  g2: `grid-gap: 2rem;`,
  g3: `grid-gap: 3rem;`,
  g4: `grid-gap: 4rem;`,
})

export const heights = traitNamespace({
  h0: `height: 0;`,
  h1: `height: 1rem;`,
  h2: `height: 2rem;`,
  h3: `height: 4rem;`,
  h4: `height: 8rem;`,
  h5: `height: 16rem;`,
  mh1: `min-height: 1rem;`,
  mh2: `min-height: 2rem;`,
  mh3: `min-height: 4rem;`,
  mh4: `min-height: 8rem;`,
  mh5: `min-height: 16rem;`,
  h_25: `height: 25%;`,
  h_50: `height: 50%;`,
  h_75: `height: 75%;`,
  h_100: `height: 100%;`,
  vh_25: `height: 25vh;`,
  vh_50: `height: 50vh;`,
  vh_75: `height: 75vh;`,
  vh_100: `height: 100vh;`,
})

export const widths = traitNamespace({
  w1: `width: 1rem`,
  w2: `width: 2rem`,
  w3: `width: 4rem`,
  w4: `width: 8rem`,
  w5: `width: 16rem`,
  mw1: `min-width: 1rem`,
  mw2: `min-width: 2rem`,
  mw3: `min-width: 4rem`,
  mw4: `min-width: 8rem`,
  mw5: `min-width: 16rem`,
})

export const spacing = traitNamespace({
  ma: 'margin: auto;',
  mta: 'margin-top: auto;',
  mba: 'margin-bottom: auto;',
  mla: 'margin-left: auto;',
  mra: 'margin-right: auto;',
  mva: 'margin-top: auto; margin-bottom: auto;',
  mha: 'margin-left: auto; margin-right: auto;',
  pa: 'padding: auto;',
  pta: 'padding-top: auto;',
  pba: 'padding-bottom: auto;',
  pla: 'padding-left: auto;',
  pra: 'padding-right: auto;',
  pva: 'padding-top: auto; padding-bottom: auto;',
  pha: 'padding-left: auto; padding-right: auto;',
  m0: 'margin: 0;',
  mt0: 'margin-top: 0;',
  mb0: 'margin-bottom: 0;',
  ml0: 'margin-left: 0;',
  mr0: 'margin-right: 0;',
  mv0: 'margin-top: 0; margin-bottom: 0;',
  mh0: 'margin-left: 0; margin-right: 0;',
  p0: 'padding: 0;',
  pt0: 'padding-top: 0;',
  pb0: 'padding-bottom: 0;',
  pl0: 'padding-left: 0;',
  pr0: 'padding-right: 0;',
  pv0: 'padding-top: 0; padding-bottom: 0;',
  ph0: 'padding-left: 0; padding-right: 0;',
  m025: 'margin: 0.25rem;',
  mt025: 'margin-top: 0.25rem;',
  mb025: 'margin-bottom: 0.25rem;',
  ml025: 'margin-left: 0.25rem;',
  mr025: 'margin-right: 0.25rem;',
  mv025: 'margin-top: 0.25rem; margin-bottom: 0.25rem;',
  mh025: 'margin-left: 0.25rem; margin-right: 0.25rem;',
  p025: 'padding: 0.25rem;',
  pt025: 'padding-top: 0.25rem;',
  pb025: 'padding-bottom: 0.25rem;',
  pl025: 'padding-left: 0.25rem;',
  pr025: 'padding-right: 0.25rem;',
  pv025: 'padding-top: 0.25rem; padding-bottom: 0.25rem;',
  ph025: 'padding-left: 0.25rem; padding-right: 0.25rem;',
  m05: 'margin: 0.5rem;',
  mt05: 'margin-top: 0.5rem;',
  mb05: 'margin-bottom: 0.5rem;',
  ml05: 'margin-left: 0.5rem;',
  mr05: 'margin-right: 0.5rem;',
  mv05: 'margin-top: 0.5rem; margin-bottom: 0.5rem;',
  mh05: 'margin-left: 0.5rem; margin-right: 0.5rem;',
  p05: 'padding: 0.5rem;',
  pt05: 'padding-top: 0.5rem;',
  pb05: 'padding-bottom: 0.5rem;',
  pl05: 'padding-left: 0.5rem;',
  pr05: 'padding-right: 0.5rem;',
  pv05: 'padding-top: 0.5rem; padding-bottom: 0.5rem;',
  ph05: 'padding-left: 0.5rem; padding-right: 0.5rem;',
  m066: 'margin: 0.667rem;',
  mt066: 'margin-top: 0.667rem;',
  mb066: 'margin-bottom: 0.667rem;',
  ml066: 'margin-left: 0.667rem;',
  mr066: 'margin-right: 0.667rem;',
  mv066: 'margin-top: 0.667rem; margin-bottom: 0.667rem;',
  mh066: 'margin-left: 0.667rem; margin-right: 0.667rem;',
  p066: 'padding: 0.667rem;',
  pt066: 'padding-top: 0.667rem;',
  pb066: 'padding-bottom: 0.667rem;',
  pl066: 'padding-left: 0.667rem;',
  pr066: 'padding-right: 0.667rem;',
  pv066: 'padding-top: 0.667rem; padding-bottom: 0.667rem;',
  ph066: 'padding-left: 0.667rem; padding-right: 0.667rem;',
  m1: 'margin: 1rem;',
  mt1: 'margin-top: 1rem;',
  mb1: 'margin-bottom: 1rem;',
  ml1: 'margin-left: 1rem;',
  mr1: 'margin-right: 1rem;',
  mv1: 'margin-top: 1rem; margin-bottom: 1rem;',
  mh1: 'margin-left: 1rem; margin-right: 1rem;',
  p1: 'padding: 1rem;',
  pt1: 'padding-top: 1rem;',
  pb1: 'padding-bottom: 1rem;',
  pl1: 'padding-left: 1rem;',
  pr1: 'padding-right: 1rem;',
  pv1: 'padding-top: 1rem; padding-bottom: 1rem;',
  ph1: 'padding-left: 1rem; padding-right: 1rem;',
  m15: 'margin: 1.5rem;',
  mt15: 'margin-top: 1.5rem;',
  mb15: 'margin-bottom: 1.5rem;',
  ml15: 'margin-left: 1.5rem;',
  mr15: 'margin-right: 1.5rem;',
  mv15: 'margin-top: 1.5rem; margin-bottom: 1.5rem;',
  mh15: 'margin-left: 1.5rem; margin-right: 1.5rem;',
  p15: 'padding: 1.5rem;',
  pt15: 'padding-top: 1.5rem;',
  pb15: 'padding-bottom: 1.5rem;',
  pl15: 'padding-left: 1.5rem;',
  pr15: 'padding-right: 1.5rem;',
  pv15: 'padding-top: 1.5rem; padding-bottom: 1.5rem;',
  ph15: 'padding-left: 1.5rem; padding-right: 1.5rem;',
  m2: 'margin: 2rem;',
  mt2: 'margin-top: 2rem;',
  mb2: 'margin-bottom: 2rem;',
  ml2: 'margin-left: 2rem;',
  mr2: 'margin-right: 2rem;',
  mv2: 'margin-top: 2rem; margin-bottom: 2rem;',
  mh2: 'margin-left: 2rem; margin-right: 2rem;',
  p2: 'padding: 2rem;',
  pt2: 'padding-top: 2rem;',
  pb2: 'padding-bottom: 2rem;',
  pl2: 'padding-left: 2rem;',
  pr2: 'padding-right: 2rem;',
  pv2: 'padding-top: 2rem; padding-bottom: 2rem;',
  ph2: 'padding-left: 2rem; padding-right: 2rem;',
  m3: 'margin: 3rem;',
  mt3: 'margin-top: 3rem;',
  mb3: 'margin-bottom: 3rem;',
  ml3: 'margin-left: 3rem;',
  mr3: 'margin-right: 3rem;',
  mv3: 'margin-top: 3rem; margin-bottom: 3rem;',
  mh3: 'margin-left: 3rem; margin-right: 3rem;',
  p3: 'padding: 3rem;',
  pt3: 'padding-top: 3rem;',
  pb3: 'padding-bottom: 3rem;',
  pl3: 'padding-left: 3rem;',
  pr3: 'padding-right: 3rem;',
  pv3: 'padding-top: 3rem; padding-bottom: 3rem;',
  ph3: 'padding-left: 3rem; padding-right: 3rem;',
  m4: 'margin: 4rem;',
  mt4: 'margin-top: 4rem;',
  mb4: 'margin-bottom: 4rem;',
  ml4: 'margin-left: 4rem;',
  mr4: 'margin-right: 4rem;',
  mv4: 'margin-top: 4rem; margin-bottom: 4rem;',
  mh4: 'margin-left: 4rem; margin-right: 4rem;',
  p4: 'padding: 4rem;',
  pt4: 'padding-top: 4rem;',
  pb4: 'padding-bottom: 4rem;',
  pl4: 'padding-left: 4rem;',
  pr4: 'padding-right: 4rem;',
  pv4: 'padding-top: 4rem; padding-bottom: 4rem;',
  ph4: 'padding-left: 4rem; padding-right: 4rem;',
  mt15_within: `> * + * {
    margin-top: 1.5rem;
  }`,
  // from_props: flags({
  //   push_left: `margin-left: auto;`,
  //   push_right: `margin-right: auto;`
  // })
})
